*REMEMBER!*
Folder Structure: Script -> Engine -> Crystal Castles
* Add Warnings [0/1]
+ [ ] Add warnings to Character sheet, perhaps they should be on the Creature.cs component as well?
* Add a New Character Sheet Object on Creature [0/1]
+ [ ] Create a new character sheet that's created through a method that adds the two sheets
  together, and that's the sheet. Also the modifier sheet should be created as well. In fact all
  sheets should be duplicated and not reference from the same file.
* Perhaps add buttons?
+ [ ] Perhaps add buttons to make the errors easier to handle. Unsure because of all the checks that
  have to be made.
* Cursor Problem [2/4]
Make a cursor and have it hijack your mouse. Then when ever you move the mouse you move the
cursor. The cursor decides what's selected and what shows up in the ui menu.

The Main Purpose of the Cursor:
+ [ ] Be able to see in game world information.
+ [ ] Move.
+ [ ] Attack.

POSSIBLE SOLUTIONS:
1. Your cursor is a lesh, and you drag the object along. 

2. Grid snapping, when you move the cursor around it's invisable and stuff (meaning you're moving
   around a tile) but when you stop it snaps to the most local area.  Snap is done based on two
   pieces of info:

   1. Where was your last x/y coord and priotize that.
   2. Compare the greatest area of the tile.
   3. Come up with an algothrim for that.

Grid snapping system has a mouse state machine.
1. On selected Grid.
2. Mouse has moved.
3. Grab closest grid to mouse based on x and y.

SOLUTION:
Algothrim: perhaps you are looking for the greatest area between the two objects. 
* Comment Problem [0/1]
+ [ ] Figure out how to make it so when you comment it's at the start of the file.
* Behind the Wall Problem [0/1]
+ [ ] Look into the layering code. Have an outline appear over the character whenever the character
  is knowingly layered behind a tile. You can find out if a character is by looking at the layering
  algothrim.
* State Machine
** Game Loop
This has individual states in between.
1. Your Input.
2. Logic.
3. Render.
4. (Repeat)
5. End.
6. AI.
7. Back to step 1.
* Quick Notes
I did it!
* [[/Users/Getpeanuts/Documents/Emacs/Hotkeys-Tips.org][Helpful Unity Tips]]
