*REMEMBER!*
Folder Structure: Script -> Engine -> Crystal Castles
* Divide the file Crystal/Creature
1. Have the methods that don't rely on Creature stats Crystal.
2. Then the methods that need the creature stats grab from the CreatureStat file, which is a also an
   asset.
* Cursor Problem [2/4]
Make a cursor and have it hijack your mouse. Then when ever you move the mouse you move the
cursor. The cursor decides what's selected and what shows up in the ui menu.

The Main Purpose of the Cursor:
+ [ ] Be able to see in game world information.
+ [ ] Move.
+ [ ] Attack.

POSSIBLE SOLUTIONS:
1. Your cursor is a lesh, and you drag the object along. 

2. Grid snapping, when you move the cursor around it's invisable and stuff (meaning you're moving
   around a tile) but when you stop it snaps to the most local area.  Snap is done based on two
   pieces of info:

   1. Where was your last x/y coord and priotize that.
   2. Compare the greatest area of the tile.
   3. Come up with an algothrim for that.

Grid snapping system has a mouse state machine.
1. On selected Grid.
2. Mouse has moved.
3. Grab closest grid to mouse based on x and y.

SOLUTION:
Algothrim: perhaps you are looking for the greatest area between the two objects. 
* Comment Problem [0/1]
+ [ ] Figure out how to make it so when you comment it's at the start of the file.
* Quick Notes
Figure out how to solve the component/stat problem with the Front stat and local/global height stat.
** Make Everything that shouldn't be public be private? [0/3]
1. [ ] spriteRenderer
2. [ ] creatureRaycast
3. [ ] creaturePhysic
* [[/Users/Getpeanuts/Documents/Emacs/Hotkeys-Tips.org][Helpful Unity Tips]]
