* REMEMBER! [0/1]
+ [ ] Folder Structure Script -> Engine -> Crystal Castles
* Figure out Getcomponet vs Drag Problem
+ Either have it so you have to drag the file.
+ Or it gets it by code.
* Create Image [1/1]
+ [X] Create cursor debug image.
* Cursor Problem [2/4]
Make a cursor and have it hijack your mouse. Then when ever you move the mouse you move the
cursor. The cursor decides what's selected and what shows up in the ui menu.

The Main Purpose of the Cursor:
+ [ ] Be able to see in game world information.
+ [ ] Move.
+ [ ] Attack.

POSSIBLE SOLUTIONS:
1. Your cursor is a lesh, and you drag the object along. 

2. Grid snapping, when you move the cursor around it's invisable and stuff (meaning you're moving
   around a tile) but when you stop it snaps to the most local area.  Snap is done based on two
   pieces of info:

   1. Where was your last x/y coord and priotize that.
   2. Compare the greatest area of the tile.
   3. Come up with an algothrim for that.

Grid snapping system has a mouse state machine.
1. On selected Grid.
2. Mouse has moved.
3. Grab closest grid to mouse based on x and y.

SOLUTION:
Algothrim: perhaps you are looking for the greatest area between the two objects. 
* Creature.cs [4/4]
1. [X] An error for disattached collider.
2. [X] Have it detect the wrong placement of the renderer pivot and give a warning.
3. [X] An error for no height.
4. [X] Have it declare an error if the circle collider is wrong.
   Offset: x = 4.135, y = 1.175, radius = 0.03
* Comment Problem [0/1]
+ [ ] Figure out how to make it so when you comment it's at the start of the file.
* Quick Notes
x 641.938
y 606.601
* [[/Users/Getpeanuts/Documents/Emacs/Hotkeys-Tips.org][Helpful Unity Tips]]
